server:
  port: 8081
spring:
  application:
    name: planes-backend

  datasource:
    url: "jdbc:postgresql://postgres:5432/appdb"
    username: "appuser"
    password: "apppas"

  jpa:
    hibernate:
      ddl:
        auto: update

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,httpexchanges
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    web:
      server:
        request:
          autotime:
            enabled: true
  httpexchanges:
    recording:
      enabled: true

logging:
  level:
    cards.planes.backend.config.MetricsConfig: INFO
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

lufthansa:
  client-id: ${LUFTHANSA_CLIENT_ID:74ypmwy4bdsaxx2c6hjc66jbj}
  client-secret: ${LUFTHANSA_CLIENT_SECRET:9y3upVx3We}
  base-url: https://api.lufthansa.com
  airports: FRA,MUC,HAM,BER
  airlines: LH
  fetch-days-ahead: 1
  boarding-offset-minutes: 40
  schedule:
    fetch-cron: "0 0 */4 * * *"
    cleanup-cron: "0 0 1 * * *"
